Fixed patcher... NameError interrupted whole patching process

diff --git a/lib/collmex/api/clear b/lib/collmex/api/clear
--- a/lib/collmex/api/clear
+++ b/lib/collmex/api/clear
@@ -1,8 +1,9 @@
 #!/bin/bash
-echo "Backing up line.rb"
-mv line.rb ../line_backup.rb
+echo "Doing backup of line.rb..."
+[ -f "line.rb" ] || (echo "line.rb not found. Did you choose correct directory?" && exit 1)
+mv line.rb ../line.rb.backup
 echo "Clearing directory"
 rm -rf *.rb
 echo "Restoring line.rb"
-mv ../line_backup.rb ./line.rb
+mv ../line.rb.backup ./line.rb
 echo "Done"
